# -*- coding: utf-8 -*-
"""ca2_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EU0S0rzjPGoPYUwlhOaXJnlCe5VuWcB7
"""

pip install ultralytics deep-sort-realtime opencv-python yt-dlp

import cv2
import os # Import os for path checking
import sys # Import sys for sys.exit()
from google.colab.patches import cv2_imshow # For displaying video in Colab

# Ensure video_path points to the file in the Colab environment.
# The kernel state lists '/content/crosswalk.mp4' as an available file.
video_path = '/content/crosswalk.mp4' # Update this to the correct path in Colab

# Check if the file actually exists at the Colab path before trying to open.
# This adds a more specific error message if the file is truly missing.
if not os.path.isfile(video_path):
  print(f"Error: Video file not found at '{video_path}'. Please ensure it's uploaded or downloaded to this location.")
  sys.exit(1)

# Try opening the video using the corrected path
cap = cv2.VideoCapture(video_path)

if not cap.isOpened():
  print(f"Error: The video file '{video_path}' exists but could not be opened.")
  print("It might be corrupted or in an unsupported format.")
  sys.exit(1)

print("Video opened successfully.")

# Define a frame limit to prevent excessive output in Colab
frame_limit = 100 # Display only the first 100 frames
frame_count = 0

# --- Video playback loop ---
while True:
    ret, frame = cap.read()

    if not ret:
        print("End of video or error reading frame.")
        break

    # Use cv2_imshow for displaying frames in Colab notebooks.
    # This is a Colab-specific function, as cv2.imshow does not work here.
    cv2_imshow(frame)

    frame_count += 1
    if frame_count >= frame_limit:
        print(f"Stopped after displaying {frame_limit} frames to prevent excessive output. You can adjust 'frame_limit' to see more.")
        break

    # In Colab, cv2.waitKey does not work as it requires a GUI environment.
    # The loop will continue until the end of the video or the frame_limit is reached.
    # If you need to stop early, you can manually stop the cell execution.

cap.release()
cv2.destroyAllWindows()
print("Video closed.")

from ultralytics import YOLO
model = YOLO("yolov8n.pt")

from deep_sort_realtime.deepsort_tracker import DeepSort
tracker = DeepSort(max_age=30)

